### ISSUE TITLE
Using double equals for floating point comparison

### ISSUE THREAD

**Issue by jay3ss** [CSULATeleop/teleop#2]
Starting on [line 76 of `titl_mechanism_10_15__17.ino`](https://github.com/CSULATeleop/teleop/blob/dev/arduino/titl_mechanism_10_15_17/titl_mechanism_10_15_17.ino#L76) a double equals (`==`) is used to compare a floating point value. This isn't the best way to do comparisons with floating point numbers due to the internal representation of floating points in computers. What should be used is a range of values, i.e., `1.9 <= 2.0 <= 2.1`, but with `C++`. This will give you some wiggle room with a joy stick as well should you decide to use one.

**Comment by jreyes81** [comment]
Thanks for the feedback. Well will try to fix it during this week as we are trying to optimize/implement different subsystems on the bot.

**Comment by moxo26** [comment]
Thanks I have addressed the issue in the new file, i have decided to use the the int values obtained from the joy node.

**Comment by jay3ss** [comment]
Excellent.
